import type { Plan, ProjectionResult } from './types';
import { formatCurrency, formatPercent, formatAge } from './format';
import { getReadinessSummary } from './engine';

const prettify = (s: string): string =>
  s.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

/**
 * Export a plan + projections as a Markdown summary.
 * Designed to be Obsidian-friendly — drop the .md file into your vault.
 */
export function exportMarkdown(plan: Plan, results: ProjectionResult[]): string {
  const lines: string[] = [];

  lines.push(`# ${plan.name}`);
  lines.push('');
  lines.push(`> Generated by Retirement Planner on ${new Date().toLocaleDateString()}`);
  lines.push('');

  // Overall summary table
  lines.push('## Scenario Summary');
  lines.push('');
  lines.push('| Scenario | Outcome | Nest Egg at Retirement | Final Assets (Real) | Depletion Age |');
  lines.push('|----------|---------|----------------------|--------------------|---------------|');
  for (const r of results) {
    const scenario = plan.scenarios.find((s) => s.id === r.scenarioId);
    if (!scenario) continue;
    const readiness = getReadinessSummary(r, scenario.assumptions.retirementAge, scenario.assumptions.safeWithdrawalRate);
    lines.push(
      `| ${r.scenarioName} | ${r.success ? '✅ Sustainable' : '❌ Depleted'} | ${formatCurrency(readiness.nestEggAtRetirementReal)} | ${formatCurrency(r.finalAssetsReal)} | ${formatAge(r.depletionAge)} |`,
    );
  }
  lines.push('');

  // Per-scenario detail
  for (const r of results) {
    const scenario = plan.scenarios.find((s) => s.id === r.scenarioId);
    if (!scenario) continue;
    const a = scenario.assumptions;
    const readiness = getReadinessSummary(r, a.retirementAge, a.safeWithdrawalRate);

    lines.push(`## ${r.scenarioName}`);
    lines.push('');

    // Assumptions
    lines.push('### Assumptions');
    lines.push(`- Current age: **${a.currentAge}** → Retire at **${a.retirementAge}** → Plan to **${a.endAge}**`);
    lines.push(`- Inflation: **${formatPercent(a.inflationRate)}** | SS COLA: **${formatPercent(a.socialSecurityCola)}** | Tax rate: **${formatPercent(a.retirementTaxRate)}**`);
    lines.push(`- Safe withdrawal rate: **${formatPercent(a.safeWithdrawalRate)}**`);
    lines.push('');

    // Key results
    lines.push('### Key Results');
    lines.push(`- **Outcome:** ${r.success ? '✅ Sustainable' : '❌ Runs out of money'}`);
    if (!r.success) lines.push(`- **Depleted at age:** ${formatAge(r.depletionAge)}`);
    lines.push(`- **Nest egg at retirement:** ${formatCurrency(readiness.nestEggAtRetirement)} (${formatCurrency(readiness.nestEggAtRetirementReal)} in today's dollars)`);
    lines.push(`- **First-year withdrawal rate:** ${formatPercent(readiness.neededWithdrawalRate)} (safe: ${formatPercent(a.safeWithdrawalRate)})`);
    lines.push(`- **Final assets:** ${formatCurrency(r.finalAssets)} (${formatCurrency(r.finalAssetsReal)} real)`);
    lines.push('');

    // Accounts
    if (scenario.accounts.length > 0) {
      lines.push('### Accounts');
      lines.push('| Account | Type | Balance | Return | Contribution | Match |');
      lines.push('|---------|------|---------|--------|-------------|-------|');
      for (const acct of scenario.accounts) {
        lines.push(`| ${acct.name} | ${prettify(acct.type)} | ${formatCurrency(acct.balance)} | ${formatPercent(acct.annualReturn)} | ${formatCurrency(acct.annualContribution)} | ${formatCurrency(acct.employerMatch)} |`);
      }
      lines.push('');
    }

    // Expenses
    if (scenario.expenses.length > 0) {
      lines.push('### Expenses');
      lines.push('| Expense | Category | Annual | Pre-Ret | Post-Ret |');
      lines.push('|---------|----------|--------|---------|----------|');
      for (const exp of scenario.expenses) {
        lines.push(`| ${exp.name} | ${prettify(exp.category)} | ${formatCurrency(exp.annualAmount)} | ${exp.preRetirement ? '✓' : ''} | ${exp.postRetirement ? '✓' : ''} |`);
      }
      lines.push('');
    }

    // Income
    if (scenario.incomeSources.length > 0) {
      lines.push('### Retirement Income');
      lines.push('| Source | Type | Annual | Starts | Ends | COLA |');
      lines.push('|--------|------|--------|--------|------|------|');
      for (const inc of scenario.incomeSources) {
        lines.push(`| ${inc.name} | ${prettify(inc.type)} | ${formatCurrency(inc.annualAmount)} | ${inc.startAge} | ${inc.endAge ?? '—'} | ${inc.cola ? '✓' : ''} |`);
      }
      lines.push('');
    }

    // Events
    if (scenario.events.length > 0) {
      lines.push('### Life Events');
      lines.push('| Event | Type | Age | Cost | Proceeds | Ongoing/Yr | Years |');
      lines.push('|-------|------|-----|------|----------|------------|-------|');
      for (const ev of scenario.events) {
        lines.push(`| ${ev.name} | ${prettify(ev.type)} | ${ev.age} | ${formatCurrency(ev.cost)} | ${formatCurrency(ev.proceeds)} | ${formatCurrency(ev.ongoingAnnualImpact)} | ${ev.ongoingDurationYears ?? '∞'} |`);
      }
      lines.push('');
    }

    // Year-by-year (key ages only to keep it readable)
    lines.push('### Projection (Selected Years)');
    lines.push('| Age | Assets (Real) | Income | Withdrawals | Expenses |');
    lines.push('|-----|--------------|--------|-------------|----------|');
    const keyAges = [a.currentAge, a.retirementAge - 1, a.retirementAge, a.retirementAge + 5, a.retirementAge + 10, a.retirementAge + 20, a.endAge];
    const uniqueAges = [...new Set(keyAges)].filter((age) => age >= a.currentAge && age <= a.endAge).sort((x, y) => x - y);
    for (const age of uniqueAges) {
      const y = r.years.find((y) => y.age === age);
      if (!y) continue;
      lines.push(`| ${y.age} | ${formatCurrency(y.realAssets)} | ${formatCurrency(y.income)} | ${formatCurrency(y.withdrawals)} | ${formatCurrency(y.expenses)} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*This file was generated by the Retirement Planner. Import the corresponding `.json` file to restore full data.*');

  return lines.join('\n');
}